server:
  port: 8080
spring:
  main:
    banner-mode: 'off'
  mvc:
    favicon:
      enabled: false
    jmx:
      enabled: true
  session:
    store-type: none
  cache:
    type: infinispan
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs
infinispan:
  remote:
    server-list: 'datagrid-demo-hotrod.datagrid-demo.svc:11333' 
